services:
  accountability-bot:
    build: .
    container_name: bother-bot
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/database.db
    restart: unless-stopped
